steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/workplace-app:$REVISION_ID", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/workplace-app:$REVISION_ID"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ["set", "image", "deployment/workplace-app-deployment", "workplace-app=gcr.io/$PROJECT_ID/workplace-app:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ic-cloud-native'